services:
  api:
    # Nu trækker vi direkte fra GitHub
    image: ghcr.io/adiljavatogo/robomonitor-api:latest
    # ports:
    #   - "5280:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # ports:
    #   - "9091:9090"
    depends_on:
      - api
    restart: always

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      # Datasource provisioning, som fortæller Grafana hvor vores datasource YAML-fil ligger
      - ./grafana_config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      
      # Dashboard provisioning, som fortæller Grafana hvor vores dashboard JSON-filer ligger
      - ./grafana_config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      
      # Selve dashboard JSON-filerne
      - ./grafana_config/dashboards:/etc/grafana/provisioning/dashboards_data
      
      # Grafana data, så vi ikke mister vores dashboards og datasource konfiguration ved genstart
      - grafana_data:/var/lib/grafana
    # ports:
    #   - "3030:3000"
    depends_on:
      - prometheus
    restart: always

  # Publisher
  python_publisher:
    # Python-images kommer nu også fra GitHub
    image: ghcr.io/adiljavatogo/scrabe-bot:latest
    # Vi overskriver standard-kommandoen til at starte pub i stedet for sub
    command: ["/bin/bash", "-c", "source install/setup.bash && ros2 run scrabe_bot_app scrabe_pub"]
    restart: always

  # Subscriber
  python_subscriber:
    image: ghcr.io/adiljavatogo/scrabe-bot:latest
    environment:
      # http://api:8080
      - ROBOMONITOR_API_URL=http://gateway:80
      - ROBOT_API_KEY=herlev_ghi789 # subscriber node henter fra miljøvariabler
    depends_on:
      - gateway # fra api til gateway, da gateway håndterer autentificering og videresender til api
    restart: always

  gateway:
    image: ghcr.io/adiljavatogo/robomonitor-gateway:latest
    # environment:
    #   # Dobbelt understregning (__) fortæller .NET, at den skal overskrive "Robot_Herlev_1" under "RobotApiKeys"
    #   - RobotApiKeys__Robot_Herlev_1=${HERLEV_REAL_KEY}
    #   - RobotApiKeys__Robot_OUH_1=${OUH_REAL_KEY}
    environment:
      # Tvinger .NET/Kestrel til at lytte på port 80 og 443 internt i containeren
      - ASPNETCORE_URLS=http://0.0.0.0:80  # https://0.0.0.0:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    restart: always

volumes:
  prometheus_data:
  grafana_data: