name: Build and Push API

on:
  push:
    branches: [ "master" ] # husk også pull reuqest
    
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: adiljavatogo/robomonitor-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: adiljavatogo
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: RoboMonitor/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Modtag event og opdater
        run: |
          echo "Pub/Sub node er blevet opdateret"
          echo "Det nye tag er: ${{ github.event.client_payload.image_tag }}"
